type: object
properties:
  name:
    type:
      - string
      - "null"
    description: Required.
  value:
    type:
      - string
      - "null"
    title: +optional
description: PodDNSConfigOption defines DNS resolver options of a pod.
$schema: http://json-schema.org/schema#
